/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.stream.Collectors;

public class Formulario extends javax.swing.JFrame {

    List<Senha> listSenha;

    Iterator<Senha> itr;

    int contador;

    public Formulario() {
        initComponents();

        listSenha = new ArrayList<Senha>();

        contador = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comunjButton1 = new javax.swing.JButton();
        rapidojButton2 = new javax.swing.JButton();
        prioritjButton3 = new javax.swing.JButton();
        senhaUsuariojLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cx1jButton4 = new javax.swing.JButton();
        cx2jButton5 = new javax.swing.JButton();
        cx3jButton6 = new javax.swing.JButton();
        cx4jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        senhaCaixasjLabel2 = new javax.swing.JLabel();
        exbCaixajLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comunjButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        comunjButton1.setText("COMUM");
        comunjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comunjButton1ActionPerformed(evt);
            }
        });

        rapidojButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        rapidojButton2.setText("RAPIDO");
        rapidojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapidojButton2ActionPerformed(evt);
            }
        });

        prioritjButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        prioritjButton3.setText("PRIORITARIO");
        prioritjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioritjButton3ActionPerformed(evt);
            }
        });

        senhaUsuariojLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        senhaUsuariojLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senhaUsuariojLabel1.setText("-----Selecione um atendimento------");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Clientes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Retire aqui sua senha");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sua senha é:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(comunjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rapidojButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prioritjButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE))
                    .addComponent(senhaUsuariojLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comunjButton1)
                    .addComponent(rapidojButton2)
                    .addComponent(prioritjButton3))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(senhaUsuariojLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cx1jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cx1jButton4.setText("Caixa-1");
        cx1jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx1jButton4ActionPerformed(evt);
            }
        });

        cx2jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cx2jButton5.setText("Caixa-2");
        cx2jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx2jButton5ActionPerformed(evt);
            }
        });

        cx3jButton6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cx3jButton6.setText("Caixa-3");
        cx3jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx3jButton6ActionPerformed(evt);
            }
        });

        cx4jButton7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cx4jButton7.setText("Caixa-4");
        cx4jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx4jButton7ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Caixas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cx1jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cx3jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cx2jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(cx4jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cx1jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cx2jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cx3jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cx4jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        senhaCaixasjLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        senhaCaixasjLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senhaCaixasjLabel2.setText("--");
        senhaCaixasjLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        exbCaixajLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        exbCaixajLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exbCaixajLabel3.setText("--");
        exbCaixajLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(senhaCaixasjLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exbCaixajLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(senhaCaixasjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(exbCaixajLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comunjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comunjButton1ActionPerformed

        contador++;
        Senha senha = new Senha("C", contador);
        listSenha.add(senha);
        senhaUsuariojLabel1.setText(String.valueOf(senha));
    }//GEN-LAST:event_comunjButton1ActionPerformed

    private void rapidojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapidojButton2ActionPerformed
        contador++;
        Senha senha = new Senha("R", contador);
        listSenha.add(senha);
        senhaUsuariojLabel1.setText(String.valueOf(senha));
    }//GEN-LAST:event_rapidojButton2ActionPerformed

    private void prioritjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prioritjButton3ActionPerformed
        contador++;
        Senha senha = new Senha("P", contador);
        listSenha.add(senha);
        senhaUsuariojLabel1.setText(String.valueOf(senha));
    }//GEN-LAST:event_prioritjButton3ActionPerformed

    private void cx1jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx1jButton4ActionPerformed

        List<Senha> filtro = listSenha.stream().filter(x -> x.toString().charAt(0) == 'P').collect(Collectors.toList());

        itr = filtro.iterator();
        if (!filtro.isEmpty()) {
            while (itr.hasNext()) {
                Senha p = itr.next();

                exbCaixajLabel3.setText("CX-1");
                exbCaixajLabel3.setForeground(Color.green);
                senhaCaixasjLabel2.setForeground(Color.green);
                senhaCaixasjLabel2.setText(p.toString());

                filtro.remove(p);
                listSenha.remove(p);
                break;
            }

        } else if (!itr.hasNext()) {
            itr = listSenha.iterator();
            while (itr.hasNext()) {

                Senha snh = itr.next();
                exbCaixajLabel3.setText("CX-1");
                senhaCaixasjLabel2.setText(snh.toString());

                itr.remove();
                break;

            }
        }


    }//GEN-LAST:event_cx1jButton4ActionPerformed

    private void cx2jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx2jButton5ActionPerformed
        List<Senha> filtro = listSenha.stream().filter(x -> x.toString().charAt(0) == 'R').collect(Collectors.toList());

        itr = filtro.iterator();
        if (!filtro.isEmpty()) {
            while (itr.hasNext()) {
                Senha r = itr.next();

                exbCaixajLabel3.setText("CX-2");
                exbCaixajLabel3.setForeground(Color.blue);
                senhaCaixasjLabel2.setForeground(Color.blue);
                senhaCaixasjLabel2.setText(r.toString());

                filtro.remove(r);
                listSenha.remove(r);
                break;
            }

        } else if (!itr.hasNext()) {
            itr = listSenha.iterator();
            while (itr.hasNext()) {

                Senha snh = itr.next();
                exbCaixajLabel3.setText("CX-2");
                senhaCaixasjLabel2.setText(snh.toString());

                itr.remove();
                break;

            }
        }

    }//GEN-LAST:event_cx2jButton5ActionPerformed

    private void cx3jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx3jButton6ActionPerformed
        List<Senha> filtro = listSenha.stream().filter(x -> x.toString().charAt(0) == 'R').collect(Collectors.toList());

        itr = filtro.iterator();
        if (!filtro.isEmpty()) {
            while (itr.hasNext()) {
                Senha r = itr.next();

                exbCaixajLabel3.setText("CX-3");
                exbCaixajLabel3.setForeground(Color.blue);
                senhaCaixasjLabel2.setForeground(Color.blue);
                senhaCaixasjLabel2.setText(r.toString());

                filtro.remove(r);
                listSenha.remove(r);
                break;
            }

        } else if (!itr.hasNext()) {
            itr = listSenha.iterator();
            while (itr.hasNext()) {

                Senha snh = itr.next();
                exbCaixajLabel3.setText("CX-3");
                senhaCaixasjLabel2.setText(snh.toString());

                itr.remove();
                break;

            }
        }

    }//GEN-LAST:event_cx3jButton6ActionPerformed

    private void cx4jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx4jButton7ActionPerformed
        List<Senha> filtro = listSenha.stream().filter(x -> x.toString().charAt(0) == 'C').collect(Collectors.toList());

        itr = filtro.iterator();
        if (!filtro.isEmpty()) {
            while (itr.hasNext()) {
                Senha c = itr.next();

                exbCaixajLabel3.setText("CX-4");
                exbCaixajLabel3.setForeground(Color.magenta);
                senhaCaixasjLabel2.setForeground(Color.magenta);
                senhaCaixasjLabel2.setText(c.toString());

                filtro.remove(c);
                listSenha.remove(c);
                break;
            }

        } else if (!itr.hasNext()) {
            itr = listSenha.iterator();
            while (itr.hasNext()) {

                Senha snh = itr.next();
                exbCaixajLabel3.setText("CX-4");
                senhaCaixasjLabel2.setText(snh.toString());

                itr.remove();
                break;

            }
        }


    }//GEN-LAST:event_cx4jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comunjButton1;
    private javax.swing.JButton cx1jButton4;
    private javax.swing.JButton cx2jButton5;
    private javax.swing.JButton cx3jButton6;
    private javax.swing.JButton cx4jButton7;
    private javax.swing.JLabel exbCaixajLabel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton prioritjButton3;
    private javax.swing.JButton rapidojButton2;
    private javax.swing.JLabel senhaCaixasjLabel2;
    private javax.swing.JLabel senhaUsuariojLabel1;
    // End of variables declaration//GEN-END:variables
}
